# Generated by Django 4.2.6 on 2023-11-28 18:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.CharField(default=api.models.generate_unique_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('photo', models.TextField()),
                ('category', models.CharField(choices=[('Haute Personnalité', 'Haute Personnalité'), ('Invité', 'Invité'), ('Jury et organisme de contrôle', 'Jury et organisme de contrôle'), ('Délagation', 'Délagation'), ('Organisation', 'Organisation'), ('Presse', 'Presse'), ('Radio télé difiseur', 'Radio télé difiseur'), ('Bénévole', 'Bénévole')], max_length=50)),
                ('fonction', models.CharField(choices=[('Haute Personnalité', 'Haute Personnalité'), ('Invité', 'Invité'), ('Président du jury', 'Président du jury'), ('Délégation technique sportif', 'Délégation technique sportif'), ('Officiel sport', 'Officiel sport'), ('Juré culturel', 'Juré culturel'), ('Antidopage', 'Antidopage'), ('Officiel', 'Officiel'), ('Membre du gouvernement', 'Membre du gouvernement'), ('Chef de délagation', 'Chef de délagation'), ('Chef de mission', 'Chef de mission'), ('Administrateif', 'Administrateif'), ('Entraîneur', 'Entraîneur'), ('Technique', 'Technique'), ('Médical', 'Médical'), ('Compétiteur', 'Compétiteur'), ('CNJF', 'CNJF'), ('Officile-Org', 'Officile-Org'), ('CIJF', 'CIJF'), ('Responsable de site', 'Responsable de site'), ("Reponsable d'activité", "Reponsable d'activité"), ('Sécurité', 'Sécurité'), ('Organisateur', 'Organisateur'), ('Presse', 'Presse'), ('Média télé-radio', 'Média télé-radio'), ('Bénévole', 'Bénévole')], max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
