# Generated by Django 4.2.6 on 2023-11-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_name_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rule',
            field=models.CharField(choices=[('Chef de délagation', 'Chef de délagation'), ('Jury / Organisme de contrôle', 'Jury / Organisme de contrôle'), ('Media', 'Media')], default='Chef de délagation', max_length=50),
        ),
    ]
