# Generated by Django 4.2.6 on 2023-11-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rule',
            field=models.CharField(choices=[('Chef de délégation', 'Chef de délégation'), ('Jury / Organisme de contrôle', 'Jury / Organisme de contrôle'), ('Media', 'Media')], default='Chef de délagation', max_length=50),
        ),
    ]
