# Generated by Django 4.2.6 on 2023-11-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_rule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Participant',
        ),
    ]
