# Generated by Django 4.2.6 on 2023-11-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_participant_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='fonction',
            new_name='function',
        ),
    ]
