# Generated by Django 4.2.6 on 2023-11-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_fonction_participant_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('Haute Personnalité', 'Haute Personnalité'), ('Invité', 'Invité'), ('Jury et organisme de contrôle', 'Jury et organisme de contrôle'), ('Délégation', 'Délégation'), ('Organisation', 'Organisation'), ('Presse', 'Presse'), ('Radio télé difiseur', 'Radio télé difiseur'), ('Bénévole', 'Bénévole')], max_length=50),
        ),
    ]
